"""
Data Profiler

This module loads all CSV datasets from the raw data directory,
profiles each dataset, prints a summary to the terminal,
and generates a Markdown profiling report.
"""

from src.config.paths import PROFILING_REPORT, RAW_DATA_DIR

import pandas as pd



def load_datasets() -> dict[str, pd.DataFrame]:
    """
    Load all CSV datasets from the raw data directory.

    Returns:
        Dictionary where:
        - key = filename without extension
        - value = pandas DataFrame
    """

    datasets: dict[str, pd.DataFrame] = {}

    csv_files = sorted(RAW_DATA_DIR.glob("*.csv"))

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV files found in '{RAW_DATA_DIR}'."
        )

    for csv_file in csv_files:
        dataframe = pd.read_csv(csv_file)
        datasets[csv_file.stem] = dataframe

    return datasets


def profile_dataset(
    dataset_name: str,
    dataframe: pd.DataFrame,
) -> None:
    """
    Display profiling statistics for a dataset.

    Args:
        dataset_name: Name of the dataset.
        dataframe: Dataset to profile.
    """

    print("\n" + "=" * 60)
    print(f"Dataset: {dataset_name}.csv")
    print("=" * 60)

    print(f"Rows: {dataframe.shape[0]}")
    print(f"Columns: {dataframe.shape[1]}")

    print("\nColumn Names:")
    for column in dataframe.columns:
        print(f" - {column}")

    print("\nData Types:")
    print(dataframe.dtypes)

    print("\nMissing Values:")
    print(dataframe.isnull().sum())

    print("\nDuplicate Rows:")
    print(dataframe.duplicated().sum())

    numeric_columns = dataframe.select_dtypes(include="number")

    if not numeric_columns.empty:
        print("\nNumerical Summary:")
        print(numeric_columns.describe())

    categorical_columns = dataframe.select_dtypes(
        include=["object", "string", "category", "str"]
    )

    if not categorical_columns.empty:
        print("\nCategorical Summary:")

        for column in categorical_columns.columns:
            print(f"\n{column}")
            print(dataframe[column].value_counts().head())


def save_markdown_report(
    datasets: dict[str, pd.DataFrame],
) -> None:
    """
    Generate a Markdown profiling report.

    Args:
        datasets: Dictionary containing all loaded datasets.
    """

    PROFILING_REPORT.parent.mkdir(parents=True, exist_ok=True)

    with PROFILING_REPORT.open("w", encoding="utf-8") as report:

        report.write("# Data Profiling Report\n\n")
        report.write(
            "This report was automatically generated by "
            "`src/profiling/data_profiler.py`.\n\n"
        )

        for dataset_name, dataframe in datasets.items():

            report.write(f"## {dataset_name}.csv\n\n")

            report.write(f"- **Rows:** {dataframe.shape[0]}\n")
            report.write(f"- **Columns:** {dataframe.shape[1]}\n")
            report.write(
                f"- **Duplicate Rows:** {dataframe.duplicated().sum()}\n\n"
            )

            report.write("### Column Data Types\n\n")

            report.write("| Column | Data Type |\n")
            report.write("|--------|-----------|\n")

            for column, dtype in dataframe.dtypes.items():
                report.write(f"| {column} | {dtype} |\n")

            report.write("\n")

            report.write("### Missing Values\n\n")

            report.write("| Column | Missing |\n")
            report.write("|--------|---------|\n")

            missing_values = dataframe.isnull().sum()

            for column, missing in missing_values.items():
                report.write(f"| {column} | {missing} |\n")

            report.write("\n---\n\n")

    print("\n" + "=" * 60)
    print(f"Profiling report saved to: {PROFILING_REPORT}")
    print("=" * 60)


def main() -> None:
    """
    Entry point for dataset profiling.
    """

    datasets = load_datasets()

    print("=" * 60)
    print("Seller Trust Analytics Platform")
    print("Dataset Profiling")
    print("=" * 60)

    for name, dataframe in datasets.items():
        profile_dataset(name, dataframe)

    save_markdown_report(datasets)


if __name__ == "__main__":
    main()